name: test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    name: "Test on Node.js ${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
      - name: Test Generate RSS
        run: yarn run main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
